```{r}
require(knitr)
require(vegan)
require(ALDEx2)
library(xtable)
require(stats)
library(compositions)
library(zCompositions)
library(tidyverse)

# rdirchlet function
rdirichlet <- function (n, alpha) {  
  if(length(n) > 1) n <- length(n)
  if(n < 0) stop("value(n) can not be negative in rtriang")
  if(is.vector(alpha)) alpha <- t(alpha)
  l <- dim(alpha)[2]
  x <- matrix(rgamma(l * n, t(alpha)), ncol = l, byrow=TRUE) # 
  return(x / rowSums(x))
}


# make sure we get the same random numbers every time
set.seed(6)
# generate the data, it is just random uniform
s1 <- c(runif(50, min=1e8, max=1e10))
s1[50] <- 2e10
s2 <- s1 * runif(length(s1), min=0.8, max=1.2)
s2[50] <- 2e11
s <- cbind(s1,as.vector(s2))
# proportions with a little bit of multivariate Poisson
# randomness added in
s.p <- apply(s,2,function(x){rdirichlet(1,(x/(0.0001*sum(x))))})
# clr
s.clr <- apply(s.p,2, function(x){log2(x) - mean(log2(x))})
# define variables for use later in the text 
# number of the variable that changes 
n.start <- s1[50]
n.end <- s2[50]
p.start <- round(s.p[50,1] * 100, 1)
p.end <- round(s.p[50,2] * 100, 1)
sum.s1 <- round(sum(s1)/1e9,1)
sum.s2 <- round(sum(s2)/1e9,1)

par(mfrow=c(1,2), mar=c(2,3,3,1))
  plot(s, log="xy", pch=19, col="red", cex=0.8, main="Counts")
  points(s[50,1],s[50,2], pch=19, col="blue", cex=0.8)
  abline(0,1, col="grey", lty=2, lwd=2)
  plot(s.p, log="xy", pch=19, col="red" , cex=0.8, main="Proportions")
  points(s.p[50,1],s.p[50,2], pch=19, col="blue", cex=0.8)
  abline(0,1, col="grey", lty=2, lwd=2)

  # simulation of a 4-part composition
  # based on a log-normal distribution with
  # a given log-mean and log-covariance.
  # This simulation is rounded to counts using
  # ceiling function (this avoid zeroes in the data set)
  # goal: show problems with spurious correlation
  #     scaterplots correlation  1,2 ; 1,3
  # set log-means
  mu = c(5,3,4,6)
  # set log-covariances (must be symmetric) 
  ycov = rbind( c( 5.0,-4.0, 0.1,-1.0),
                c(-4.0, 4.0, 1.0, 1.5),
                c( 0.1, 1.0, 2.0, 0.5),
                c(-1.0, 1.5, 0.5, 6.0) )
  # check positive definiteness
  ycoveigen = eigen(ycov)
  # ycoveigen£values # must be posiitve
  # corresponding log-correlation matrix
  ycor = diag(1/sqrt(diag(ycov))) %*% ycov %*% diag(1/sqrt(diag(ycov)))
  # simulate a multivariate normal 100-sample
  y = unclass(rnorm.rmult(100,mu,ycov) ) # compute lognormal sample
  x = exp(y)
  # transform into counts
  xcounts = ceiling(x)
  # proportions complete composition 1:4
  sumc = outer( rowSums(xcounts), rep(1,ncol(xcounts)))
  xpropc = xcounts/sumc
  # proportions subcomposition 1:3
  xcountsub = xcounts[,1:3]
  sumsub = outer( rowSums(xcountsub), rep(1,ncol(xcountsub)))
  xpropsub = xcountsub/sumsub
  corxcounts=cor(xcounts)
  corsub=cor(xpropsub)
  corc=cor(xpropc)
  # correlation plots 1,2 parts
  # pdf(file="fig-rho12.pdf",width=5,height=5,family="Times") par(mfrow=c(1,2))
  xxc = xpropc[,c(1,2)]
  xxsub = xpropsub[,c(1,2)]
  clab=round(corc[1,2],3)
  sublab=round(corsub[1,2],3)
plot(xxc,col="blue",xlim=c(0,1),ylim=c(0,1),
     xlab="proportion 1",ylab="proportion 2")
     points(xxsub,col="red")
     text(x=0.7,y=0.9,
       labels=paste("blue: 4-part, rho(1,2)=",clab), cex=0.6 )
       text(x=0.7,y=0.8,
         labels=paste("red: 3-part, rho(1,2)=",sublab), cex=0.6 ) # dev.off()
# correlation plots 1,3 parts
# pdf(file="fig-rho13.pdf",width=5,height=5,family="Times") xxc = xpropc[,c(1,3)]
xxsub = xpropsub[,c(1,3)]
clab=round(corc[1,3],3)
sublab=round(corsub[1,3],3) 
plot(xxc,col="blue",xlim=c(0,1),ylim=c(0,1),
     xlab="proportion 1",ylab="proportion 3")
     points(xxsub,col="red")
     text(x=0.7,y=0.9,
       labels=paste("blue: 4-part, rho(1,3)=",clab), cex=0.6  )
       text(x=0.7,y=0.8,
         labels=paste("red: 3-part, rho(1,3)=",sublab), cex=0.6 ) # dev.off()
         
library(here)
d.bf.0 <- read.table("https://raw.githubusercontent.com/ggloor/CoDaSeq/master/tongue_vs_cheek.txt", header=T, row.names=1, sep="\t")
#write.csv(d.bf.0, here("data/biplot_tut.csv"))
d.bf.0
tax.0 <- d.bf.0$tax
d.bf.0$tax <- NULL
# for the supplement figure keep only those found in at least # 10% the samples to keep it simple
cutoff = .1
d.subset <- data.frame(d.bf.0[which(apply(d.bf.0, 1,
  function(x){length(which(x != 0))/length(x)}) > cutoff),]) 
tax.subset <- tax.0[which(apply(d.bf.0, 1,
  function(x){length(which(x != 0))/length(x)}) > cutoff)] 

# change full names to the last taxonomic name
short_tax <- gsub(".+__", "", tax.subset)
# get a count of tongue and cheek samples
com <- c(rep("T", length(grep("td_.", colnames(d.subset))) ),
    rep("C", length(grep("bm_.", colnames(d.subset))) ))
# here we correct using the count zero multiplicative # method from the zCompositons package
d.n0 <- cmultRepl(t(d.subset), label=0, method="CZM")

# center log-ratio transform
d.n0.clr <- apply(d.n0, 2, function(x){log(x) - mean(log(x))})
# add short row and column names
colnames(d.n0.clr) <- short_tax
rownames(d.n0.clr) <- com
# set up conditons for coloring
conds <- data.frame(c(rep(1,length(grep("td_", colnames(d.bf.0)))),
    rep(2, length(grep("bm_", colnames(d.bf.0))))))
colnames(conds.b) <- "cond"
palette=palette(c("darkcyan","coral3"))
# do the SVD
pcx <- prcomp(d.n0.clr)
# compute metric variance, compositons package
mvar.clr <- mvar(d.n0.clr)
#plot it
par(mfrow=c(1,2))
# this is the biplot from the paper with OTUs present in 66% of samples
coloredBiplot(pcx,col=rgb(0,0,0,0.1),cex=c(0.6,0.4), xlabs.col=conds$cond,
 xlab=paste("PC1: ", round(sum(pcx$sdev[1]^2)/mvar.clr, 3), sep=""),
 ylab=paste("PC2: ", round(sum(pcx$sdev[2]^2)/mvar.clr, 3), sep=""),
 var.axes=T, arrow.len=0.05,scale=0)
# this is the biplot with OTUs present in 10% of samples
coloredBiplot(pcx.b,col=rgb(0,0,0,0.1),cex=c(0.6,0.4), xlabs.col=conds.b$cond,
 xlab=paste("PC1: ", round(sum(pcx.b$sdev[1]^2)/mvar.clr.b, 3), sep=""),
 ylab=paste("PC2: ", round(sum(pcx.b$sdev[2]^2)/mvar.clr.b, 3), sep=""),
var.axes=T, arrow.len=0.05,scale=0)
```


That code is not leading to output in the supplement... Hopefully the following:

```{r}
##########
# using the supplementary table from Hsio et al, 2013, Cell Microbiota Modulate
# Behavioral and Physiological Abnormalities Associated with Neurodevelopmental
# Disorders
# this shows how I read the table and formatted it for ALDEx2
# d <- read.table("Hsiao_cell/cell7251mmc2/otu_table_S_P_P+Bf.csv", header=T,
#    row.names=1, sep=",",skip=1, comment.char="")
#
# #put taxonomy into a new variable and then delete
# tax <- d£taxonomy
# d£taxonomy <- NULL
# d.sub <- d[,c.d[1:20]]
#
# # reduce to OTUs that contain at least 5 counts
# # this reduces to 703 OTUs
# tax.gt5 <- data.frame(tax[which(apply(d.sub,1,sum) > 4)])
# rownames(tax.gt5) <- rownames(d.subgt5)
# d.subgt5 <- data.frame(d.sub[which(apply(d.sub,1,sum) > 4),])
#
# this is a subset of the Hsiao supplementary table dealing only with
# the B. fragilis and its control, this is the table we will use
# in both cases the OTU is the row name
# write.table(d.subgt5, file="hsiao5.txt", sep="\t", quote=F, col.names=NA)
# write.table(tax.gt5, file="tax.txt", sep="\t", quote=F, col.names=NA) # ##########
# to read the OTU table
d.h <- read.table("https://raw.githubusercontent.com/ggloor/CJM_Supplement/1.0/chunk/hsiao5.txt", header=T, row.names=1)
#write.csv(d.h, here("data/biplot_tut_hsiao.csv"))

# this follows directly from the biplot examples above
d.n0 <- cmultRepl(t(d.h), label=0, method="CZM")
rownames(d.n0) <- gsub("PolyIC...B", "B", rownames(d.n0)) 
rownames(d.n0) <- gsub("Poly", "", rownames(d.n0))
d.n0.clr.h <- t(apply(d.n0, 1, function(x){log2(x) - mean(log2(x))}))
conds <- data.frame(c(rep(1,10), rep(2,10)))
colnames(conds) <- "cond"
palette=palette(c("coral3","darkcyan"))

pcx.h <- prcomp(d.n0.clr.h)

mvar.clr.h <- mvar(d.n0.clr.h)
coloredBiplot(pcx.h,col=rgb(0,0,0,0.3),cex=c(0.7,0.4), xlabs.col=conds$cond,
    xlab=paste("PC1: ", round(sum(pcx.h$sdev[1]^2)/mvar.clr.h, 3), sep=""),
    ylab=paste("PC2: ", round(sum(pcx.h$sdev[2]^2)/mvar.clr.h, 3), sep=""),
    xlim=c(-20,25), var.axes=T, arrow.len=0.05, scale=0)
otus_loading[otus_loading$otus == "62",]


df <- d.n0.clr.h %>% as.data.frame() %>% rownames_to_column("sample_id")
df <- pcx.h$x %>% as.data.frame() %>%
  as.data.frame() %>%
  rownames_to_column("sample_id") %>%
  select(sample_id, PC1, PC2) %>%
  left_join(df, by = "sample_id")

otus_loading <- pcx.h$rotation %>% as.data.frame() %>%
  rownames_to_column("otus") %>%
  select(otus, PC1, PC2) %>%
  mutate_if(is.numeric, function(x) x*100)


ggplot(df, aes(PC1, PC2, label = sample_id)) +
  geom_text() +
  geom_text(data = otus_loading, aes(PC1, PC2, label = otus), color = "red") 






```
