# Data preparation

```{r}
# to view longer dfs I set print option
options(dplyr.print_max = 1e9)
library(microbiome)
library(tidyverse)
library(here)
# load HITChip data using Leo's script
source(here("R/read.R"))
```

```{r}
sample_data(genus) %>% as.data.frame() %>% distinct(My.SQL.ID, .keep_all = T)
```

```{r}
# load sample_data. disregard duplicate samples: %>% distinct(My.SQL.ID, .keep_all = TRUE)
# seems like this metadata is not complete. Therefore I use the excel from Gerben metadata <- sample_data(genus) 
# colnames(metadata)
metadata <- readxl::read_excel(here("data/meta_variables/my.metadata.xlsx"))
# to select the correct infants I use the resulting dataframe that arised from Gerbens selection process
select_samples <- read_csv(here("data/csv_gerben/complete.csv"))
# to confirm we have 49 pre/post for both groups
select_samples %>% group_by(childcarecenter, groupcode) %>% summarise(n = n())
metadata <- metadata %>%
    rename(subject_id = subject, sample = "Var.2") %>%
    filter(sample %in% select_samples$sample)
```

```{r}
# we have additional information stored in another excel sheet:
# I need to control for the age at CC entrace and the total length of CC (unless CC will extend)
# beyond post, which is just the indicator of the stool sample closest to post
# same for breastfeeding: I need the number or %BF until entrance and then during entrance,
# where % means breasfeedings/(breasfeedings + formula feedings), because those two variables will
# be highly correlated I assume, but I can check that...
# so the questions I need to aks are: have their been children who remained in CC after they gave their second sample?
# I assume that age at sample is in fact not the same among infants? (then 75, 105 etc. should be renamed really)
metadata2 <- readxl::read_excel(here("data/meta_variables/my.metadata2.xlsx"), sheet = "Data")
metadata2 <-
    metadata2 %>% 
        filter(ID %in% select_id$subject) %>%
        rename(
            subject_id = ID, 
            cc = Childcare_yesno,
            per_bf_during_cc = `%BEFbetweenKDV1andKDV2`, 
            weeks_cc = `Tot#KDV`, 
            bf_until_end_cc = WeeksBEF,
            age_start = Begin_age_weeks) %>%
        select(subject_id, age_start, cc, weeks_cc, bf_until_end_cc, per_bf_during_cc)
```

```{r}
# how much variation is there in the # of week subjects were in CC?
metadata2 %>% summarise(mean_weeks_cc = mean(weeks_cc), sd_weeks_cc = sd(weeks_cc))
```

```{r}
# merge metadata, rename time (because it does not correspond to real age) 
meta <- metadata %>%
    left_join(metadata2, by = "subject_id") %>%
    mutate(time = ifelse(time == "75", "pre", "post")) %>%
    select(subject_id, time, cc, age_start, weeks_cc, bf_until_end_cc, per_bf_during_cc, sample)
```

```{r}
meta
```

```{r}
# Next we need to load additional metadata about the number of week breastfeeding and formula feeding
# as can be looked up in R/read_metadata_long.R, we get a df called meta_long
# ok I see a problem: above we have bf_before_cc, which is just +1 for each week an infant had bf, thereby
# disregarding the amount of bf. E.g. infant 204 had 3 weeks but we can see below 
# that it had on average 7.5 feedings a day for those 3 weeks, which is more informative
# I think about counting the number of bf until cc, use that as a predictor and then also count the bf during cc
# actually, I will then use bf/bf+formula. Then I avoid high negative corrlation of 2 predictors and still keep
# the info for when there is no correlation (e.g. very hungry infants that got additional formula)
source(here("R/read_metadata_long.R"))
meta_long %>% filter(subject == 204, week <=16)
```

```{r}
# After I had a look at the data above, I now try to replicate the bf_weeks and then change it to a count bf_before_cc
# and a count bf_weeks_cc
meta_long <-
    meta_long %>% 
        rename(subject_id = subject) %>%
        filter(subject_id %in% meta$subject_id) %>%
        left_join(meta, by = "subject_id")
```

```{r}
# intialize columns
meta$bf_count_pre <- NA
meta$bf_count_post <- NA
meta$bf_count_cc <- NA
meta$formula_count_pre <- NA
meta$formula_count_post <- NA
meta$formula_count_cc <- NA

# select only variables needed. I checked all the infants with NA for bf, formula and exp.bf
# most of the time there is NA for bf if e.g subject was formula fed or vice versa
# if not then these are only a few rows and given the consistency, most reasonably is to insert the value
# that was given before. The infant cannot starve + it received the same number of feedings before.
# only subjects 252, 448 have critically many NA. We would need to impute or drop those 2. They are both cc
#meta_long %>% 
#    select(subject_id, bf, expressed_bf, formula, cc) %>%
#    filter(subject_id %in% c(252, 448)) %>% print()

# select subset. Then for those we know NA will be very likely the that was there before. 
#bf_bool <- 
#    ifelse(
#        is.na(bf)&is.na(expressed_bf)&is.na(formula), mean(bf, na.rm = T),
#        ifelse(
#            is.na(bf)&(!is.na(expressed_bf)|!is.na(formula)), 0, bf))
# if there is NA but there is info in the other feedings columns, then NA = 0, 
# else most likely NA = mean unless subjects are 252 and 448 (why? because mothers throughout the 
# whole data are very consistent in feedings behavior)
bf_imputed <- 
    meta_long %>%
        select(subject_id, bf, expressed_bf, formula, week, age_start, weeks_cc) %>%
        filter(!subject_id %in% c(252, 448)) %>% 
        mutate(
            bf = ifelse(is.na(bf)&(!is.na(expressed_bf)|!is.na(formula)), 0,
                ifelse(is.na(bf)&is.na(expressed_bf)&is.na(formula), mean(bf, na.rm = T), bf))) %>%
        select(subject_id, week, age_start, weeks_cc, bf)
#
expressed_bf_imputed <- 
    meta_long %>%
        select(subject_id, bf, expressed_bf, formula) %>%
        filter(!subject_id %in% c(252, 448)) %>% 
        mutate(
            expressed_bf = ifelse(is.na(expressed_bf)&(!is.na(bf)|!is.na(formula)), 0,
                ifelse(is.na(bf)&is.na(expressed_bf)&is.na(formula), mean(expressed_bf, na.rm = T), expressed_bf))) %>%
        select(expressed_bf)

#
formula_imputed <- 
    meta_long %>%
        select(subject_id, bf, expressed_bf, formula) %>%
        filter(!subject_id %in% c(252, 448)) %>% 
        mutate(
            formula = ifelse(is.na(formula)&(!is.na(bf)|!is.na(expressed_bf)), 0, 
                ifelse(is.na(bf)&is.na(expressed_bf)&is.na(formula), mean(formula, na.rm = T), formula))) %>%
        select(formula)                               
feeding_imputed <- bind_cols(bf_imputed, expressed_bf_imputed, formula_imputed)
# add expressed bf and bf together because for our research question it does not matter
feeding_imputed <- feeding_imputed %>% mutate(bf = bf + expressed_bf)
```

```{r}
feeding_imputed
```

```{r}
# now for each subject and feedintype I need to aggregate the feedings
for (id in unique(feeding_imputed$subject_id)) {
    # pre CC bf
    bf_count_pre <- 
        feeding_imputed %>% filter(subject_id == id, week <= age_start) %>%
        select(bf) %>%
            sum()/2
    meta[meta$subject_id == id, "bf_count_pre"] = bf_count_pre
    # post CC bf
    bf_count_post <- 
        feeding_imputed %>% filter(subject_id == id, week <= age_start + weeks_cc) %>%
        select(bf) %>%
            sum()/2
    meta[meta$subject_id == id, "bf_count_post"] = bf_count_post
    # during CC bf
    meta[meta$subject_id == id, "bf_count_cc"] = bf_count_post - bf_count_pre

    # pre CC formula
    formula_count_pre <- 
        feeding_imputed %>% filter(subject_id == id, week <= age_start) %>%
        select(formula) %>%
            sum()/2
    meta[meta$subject_id == id, "formula_count_pre"] = formula_count_pre
    # post CC formula
    formula_count_post <- 
        feeding_imputed %>% filter(subject_id == id, week <= age_start + weeks_cc) %>%
        select(formula) %>%
            sum()/2
    meta[meta$subject_id == id, "formula_count_post"] = formula_count_post
    # during CC formula
    meta[meta$subject_id == id, "formula_count_cc"] = formula_count_post - formula_count_pre
}
```

```{r}
# those remaining NA are as mentioned completely NA for feedings variables OR there was not even
# an excel sheet for feeding.
meta %>% filter(is.na(bf_count_pre)|is.na(bf_count_post)) %>% distinct(subject_id)
```

```{r}
test <- meta %>% mutate(check_post = bf_count_post/(age_start + weeks_cc))
# they cannot correlate perfectly since I imputed NA where they likely dropped colons. I think
# it must be that the imputed values are closer to truth since the infants did not starve...
cor.test(test$bf_until_end_cc, test$check_post)
# lets see if formula and bf correlate as I suspected
cor.test(test$bf_count_pre, test$formula_count_pre)
cor.test(test$bf_count_post, test$formula_count_post)
cor.test(test$bf_count_cc, test$formula_count_cc)
# yes...And therefore it might be reasonable to create a ratio out of them. I loose the count then but
# I trust the ratio to be more correct than the count here since the count relies on the fact that mother count
# disciplines also minor deviances and I am not sure how realistic this is...I will see. bf_ratio will
# be either the bf_ratio for the time before CC for the pre sample or the ratio in the weeks during CC (post)
# pre and post correlate highly (.8) and therefore I cannot use separate predictors in regression. I currently
# think this is a reasonable solution. 
meta <- meta %>%
    mutate(
        bf_ratio_pre = bf_count_pre/(bf_count_pre + formula_count_pre),
        bf_ratio_cc = bf_count_cc/(bf_count_cc + formula_count_cc),
        bf_ratio = ifelse(time == "pre", bf_ratio_pre, bf_ratio_cc)
    )
meta   
```

```{r}
# I will now merge the data. I later will only need to slect genus for which abundance was not high enough in any sample
# But I don't know how to do this myself yet. Then the data is ready for model fitting. 
# Another question is to impute or to use lw deletion.
# I first use lw deletion to see if everything works as expected but if possible I want to impute
# because the information about cc/nocc and time is complete and that is most important!
data <- 
    otu_table(genus) %>% 
        relative.abundance() %>%
        as.data.frame() %>%
        rownames_to_column("genus") %>%
        mutate_if(is.numeric, log10) %>%
        gather(sample, value, -genus) %>%
        spread(genus, value) %>%
        filter(sample %in% meta$sample) %>%
        left_join(meta, by = "sample") %>%
        select(colnames(meta), everything()) %>% 
        select(- bf_until_end_cc, -per_bf_during_cc) # deselecting the old vars

data <- data %>% mutate(cc = ifelse(cc == 0, "no", "yes")) %>%
                  mutate(
                      cc = factor(cc, levels = c("no", "yes")), 
                      time = factor(time, levels = c("pre", "post")),
                      bf_count_pre_s = scale(bf_count_pre)[, 1],
                      bf_count_cc_s = scale(bf_count_cc)[, 1],
                      formula_count_pre_s = scale(formula_count_pre)[, 1],
                      formula_count_cc_s = scale(bf_count_cc)[, 1],
                    )
```

```{r}
```

# Model fitting

```{r}
library(brms)
library(glue)
options(mc.cores = 4)
contrasts(data$time)
colnames(data) <- gsub(" ", "_", colnames(data))
colnames(data) <- gsub("\\.", "", colnames(data))
colnames(data)[which(colnames(data) == "Clostridium_\\(sensu_stricto\\)")] <- "Clostridium_sensu_stricto"
colnames(data) 
```

```{r}
# there is not much variation in how long they went to cc. thus age_start should be sufficient to 
# account for age
qplot(weeks_cc, data = data, geom = "density")
```

```{r}
# specify files and model options
genus <-"Enterococcus"
time <- bf(Bilophila_et_rel ~ 1 + bf_ratio + (1|subject_id), sigma ~ 1 + bf_ratio + (1|subject_id)) 
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_bf")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
```

```{r}
dt_bf <- 
    brm(
        family = student(), data = data, formula = time, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b"),
            set_prior("exponential(6)", class = "sd"),
            set_prior("normal(0, 5)", class = "Intercept"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma")
        )
)
```

```{r}
summary(dt_bf)
```

```{r}
# specify files and model options
genus <-"Bilophila_et_rel"
time <- bf(Bilophila_et_rel ~ 1 + time + (1|subject_id), sigma ~ 1 + time + (1|subject_id)) 
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_time")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
```

```{r}
dt_time <- 
    brm(
        family = student(), data = data, formula = time, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b"),
            set_prior("exponential(6)", class = "sd"),
            set_prior("normal(0, 5)", class = "Intercept"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma")
        )
)
```

```{r}
summary(dt_time)
```

```{r}
# specify files and model options
genus <-"Bilophila_et_rel"
time_cc <- bf(Bilophila_et_rel ~ 1 + time*cc + (1|subject_id), sigma ~ 1 + time*cc + (1|subject_id)) 
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_time_cc")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
# NOTE: this model had low bmfi once but not the other time...
```

```{r}
dt_time_cc <- 
    brm(
        family = student(), data = data, formula = time_cc, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b"),
            set_prior("exponential(6)", class = "sd"),
            set_prior("normal(0, 5)", class = "Intercept"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma")
        )
)
```

```{r}
summary(dt_time_cc)
```

```{r}
# specify files and model options
genus <-"Bilophila_et_rel"
time_cc_bf <- 
    bf(Bilophila_et_rel ~ 1 + time*cc + bf_ratio + (1|subject_id), sigma ~ 1 + time*cc + bf_ratio + (1|subject_id))
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_time_cc_bf_multiple")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
# i set uniform prior between 0 and 1 for the ratio.
```

```{r}
dt_time_cc_bf_multiple <- 
    brm_multiple(
        family = student(), data = test, formula = time_cc_bf, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b"),
            set_prior("exponential(6)", class = "sd"),
            set_prior("normal(0, 5)", class = "Intercept"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma")
        )
)
```

```{r}
# specify files and model options
genus <-"Bilophila_et_rel"
time_cc_bf <- 
    bf(Bilophila_et_rel ~ 1 + time*cc + bf_ratio + (1|subject_id), sigma ~ 1 + time*cc + bf_ratio + (1|subject_id))
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_time_cc_bf_multiple_test")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
# i set uniform prior between 0 and 1 for the ratio.
dt_time_cc_bf_multiple <- 
    brm_multiple(
        family = skew_normal, data = test, formula = time_cc_bf, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b"),
            set_prior("exponential(6)", class = "sd"),
            set_prior("normal(0, 5)", class = "Intercept"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma")
        )
)
```

```{r}
test <- residuals(dt_time_cc_bf_multiple)
```

```{r}
sresid <- scale(test) [, 1]
qplot(sresid, geom = "density")
```

```{r}
summary(dt_time_cc_bf_multiple)
```

```{r}
# specify files and model options
genus <-"Bilophila_et_rel"
time_cc_bf_mi <- 
    bf(Bilophila_et_rel | mi() ~ 1 + time*cc*mi(bf_ratio) + (1|subject_id), sigma ~ 1 + time*cc*mi(bf_ratio) + (1|subject_id)) +
    bf(bf_ratio | mi() ~ 1) +
    set_rescor(FALSE)
# give individual model name for storage
folder <- here("models/cc_and_feeding/distributional_t")
model_file <- glue("{folder}/{genus}_time_cc_bf_mi")
control <-  list(adapt_delta = 0.9999, max_treedepth = 15)
# i set uniform prior between 0 and 1 for the ratio.
```

```{r}
dt_time_cc_bf_mi <- 
    brm(
        family = student(), data = data, formula = time_cc_bf_mi, 
        chains = 4, iter = 3000, warmup = 1000,
        file = model_file, control = control, prior = c(
            set_prior("normal(0, 1)", class = "b", resp = "Bilophilaetrel"),
            set_prior("exponential(6)", class = "sd", resp = "Bilophilaetrel"),
            set_prior("normal(0, 5)", class = "Intercept", resp = "Bilophilaetrel"), 
            set_prior("normal(0, 1)", class = "b", dpar = "sigma", resp = "Bilophilaetrel"),
            set_prior("exponential(6)", class = "sd", dpar = "sigma", resp = "Bilophilaetrel"),
            set_prior("normal(0, 5)", class = "Intercept", dpar = "sigma", resp = "Bilophilaetrel"),
            set_prior("uniform(0, 1)", class = "Intercept", resp = "bfratio"),
            set_prior("exponential(30)", class = "sigma", resp = "bfratio")
        )
)
```

```{r}
summary(dt_time_cc_bf)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
get_prior(time_cc_bf, data = data)
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
```

```{r}
test <- data %>% 
    select(
        bf_ratio,
        subject_id, 
        time,
        cc,
        Actinomycetaceae,
        Aerococcus,
        Aeromonas,
        Akkermansia,
        Alcaligenes_faecalis_et_rel,
        Allistipes_et_rel,
        Anaerobiospirillum,
        Anaerofustis,
        Anaerostipes_caccae_et_rel,
        Anaerotruncus_colihominis_et_rel,
        Anaerovorax_odorimutans_et_rel, 
        Aneurinibacillus,
        Aquabacterium,
        Asteroleplasma_et_rel, 
        Atopobium, 
        Bacillus,
        Bacteroides_fragilis_et_rel
    )  %>% mice()
```

```{r}
test$imp
```

```{r}
colnames(data)
```

```{r}
test <- select(data, subject_id, Bilophila_et_rel, Enterococcus, Staphylococcus, time, cc, bf_ratio, age_start) %>% mice()
```

```{r}
test$loggedEvents
```

```{r}
ggplot(data, aes(, Bilophila_et_rel)) +
    geom_point() +
    geom_smooth()
```

```{r}
cor.test(data$bf_count_pre, data$formula_count_pre)
```

```{r}
test <- read_csv(here("data/csv_gerben/data1.csv"))
```

```{r}
test %>% select(subject, feeding_type) %>%
    rename(subject_id = subject) %>%
    left_join(data, by = "subject_id") %>%
    ggplot(aes(feeding_type, bf_ratio, color = feeding_type)) +
    geom_jitter(width = 0.1, alpha = 0.3)
ggsave("feeding_type_vs_bf_ratio.png")
```

```{r}
```