# 1. Introduction  

Early life stress, especially if chronic, is related to negative behavioral, cognitive and health outcomes. Entering center-based childcare (CC) at three months of life, the normal age in the Netherlands, is an important change or ‘life event’ for an infant. CC includes stressors such a long maternal separations, new and frequently changing caregivers and peers, and adaptation to a new physical environment. From our own and other studies, we know that entering childcare produces significant increases in cortisol levels as compared to levels in the home environment, and that cortisol continues to increase until at least a month after entering [@Ahnert2004; @Albers2016; @Bernard2015; @Watamura2010; @Waynforth2007]. CC has also been related to more health symptoms and illnesses including diarrhea and communicable diseases such as respiratory illnesses and otitis media [@Beijers2011; @Loeb2007].

A growing body of evidence indicates that the intestinal microbiota might play an important role in how such early life stressors influence future health outcomes and behavior. Firstly, in human studies gut microbiota composition is associated with several pediatric disorders including allergic and autoimmune diseases [@Videhult2016]. For example, @Azad2015 found a lower richness and increased _Enterobacteriaceae/Bacteroidetes_ ratio in infant stool to be associated with subsequent food sensitization in the population based Canadian Healthy Infant Longitudinal Development (CHILD) birth cohort study. Secondly, animal studies indicate that stress affects the gut microbiota, which in turn leads to inflammatory immune processes and even behavioral changes. For example, rodent studies showed that early life stress induced by maternal separation led to alternations of the intestinal barrier function and the microbiota [@Rea2016]. These alternations were accompanied by behavioral changes that in one study have been found to be mediated by the intestinal bacteria [@DePalma2015]. Interestingly, the administration of probiotics could prevent or ameliorate stress induced effects [@Rea2016]. In rhesus monkeys, maternal separation also altered the composition of the intestinal microbiota of the offspring by decreasing the number _Lactobacilli_ [@Bailey1999].  However, we lack studies that investigated the effect of early life stress on the development of the gut microbiota composition in humans and specifically the effect of CC on the infant gut microbiota composition has not been studied at all.  
Among the better studied factors that influence the development of the infant gut microbiota are diet and specifically breastfeeding. Breastfeeding increases the abundance of Lactobacilli and Bifidobacteria species when compared to formula fed infants [@Gregory2016; @Videhult2016]. @Yamada2017 described how oligosaccharides present in human breast milk selectively stimulate the growth of Bifidobacteria. Finally, there is evidence suggesting that breast milk contains bacteria that colonize the infant gut. For instance, @Pannaraj2017 describe that on average, 27.7% of the infant gut microbiome resembles the microbiome of the mother’s breast milk and 10.3% resembles the microbiome of the mother’s areolar skin. In contrast to early life stress, breastfeeding is known to be a health promoting factor in early life [@Hoddinott2008].  
Altogether, this research suggests that early life stress might impair the development of the intestinal microbiota with possible long term effects on physical health and behavior and that breastfeeding might be a protective factor against the negative influence of stress. In this study we investigated whether the entrance to CC leads to changes in the intestinal microbiota and whether breastfeeding plays a role in this relationship. We obtained stool samples from infants who entered CC (*n*=49) and control infants (*n*=49) before the entrance at 10 weeks of age (T0) and four weeks after the entrance (T1). We hypothesized (1) that we find no differences in the composition of the intestinal microbiota between infants who entered CC and control infants at T0 but that we find differences at at T1. The effect of CC might be moderated by a buffering effect of breastfeeding on microbiota changes. Therefore, (2) we anticipate a smaller change in microbiota composition in the breastfed group compared to the non breastfed group of infants that attended CC. 
   

# 2. Methods
## 2.1 Participants

As part of an ongoing longitudinal study (Bibo study), 220 mothers were followed since the third trimester of pregnancy, to investigate the influences of early caregiving factors on the early development of children. Uncomplicated singleton pregnancy, proficiency in the Dutch language, no drug use and the absence of physical and mental health problems were criteria for initial inclusion. Eight of the 220 women were excluded due to preterm birth or for other medical reasons. In addition, 19 mothers discontinued participation in the study during the first three postpartum months because of personal circumstances. All infants were healthy and born at full term ($\geq$ 37 weeks). Infants born by cesarean delivery (n=4) and who had used antibiotics (n=4) were excluded. Out of a total of 9 fecal samples that were available per infant, 2 were selected for this study: Ten weeks post-partum before entrance to CC (T0) and 4 weeks after the entrance (T1). If there was no sample obtained at both times points, the infant was excluded. Seven samples were excluded for technical reasons. For these samples, the Pearson correlation of $\>.98$ between duplicate bacterial profiles was not reached. The final sample included 49 infants per group. The study has been approved by the ethical Committee of the Faculty of Social Sciences, Radboud University Nijmegen (ECG / AvdK/07.563) and informed consent was obtained from each mother.



##  2.2 Procedure

### 2.2.1 Breastfeeding
Information about breastfeeding was collected through the use of diaries. The mothers received diaries towards the end of their pregnancy with instructions to take weekly notes about breastfeeding and bottle-feeding from week 1 until week 27 after birth. For each week, the average number of breast- and/or bottle- feedings per day were noted. We used the average number of breastfeedings per day until timepoint PRE and the average number of breastfeedings per day between timepoints PRE and POST as confounding variables in the analyses.

### 2.2.2 Faeces collection, DNA isolation and microbiota profiling
The parents were instructed to collect the fecal samples at home and to store them at -20°C. Samples were kept in coolers for transportation and then stored at -20°C and later at -80°C before being processed at the Microbiology Laboratory at Wageningen University. DNA isolation from faecal samples has been described in detail elsewhere [@Salonen2010]. In brief, DNA was isolated using a combination of column purification and Repeated-Bead-Beating.  Purity and concentration of DNA were assessed with a Nanodrop 1000 spectrophotometer (Thermo Fisher Scientific, Wilmington, USA). DNA was then stored at -20 C° pending microbial analysis. The analysis was then performed utilizing a previously benchmarked custom made, phylogenetic microarray, the Human Intestinal Tract Chip (HITChip) [@Rajilic-Stojanovic2009; @Claesson2009a]. The HITchip contains a duplicated set of 3,631 probes, which target the 16S rRNA gene sequences of more than 1,000 intestinal bacterial phylotypes [@Rajilic-Stojanovic2009]. After extraction of DNA, the full-length 16S rRNA gene was amplified, which was followed by in vitro transcription and labelling of the resulting RNA with Cy3/Cy5 before hybridization to the array. Each sample was hybridized at least twice to ensure reproducibility. Duplicate hybridizations with a Pearson correlation &lt;.98 were not considered for further analysis. By pre-processing the probe-level measurements with minimum–maximum normalization and Robust Probabilistic Averaging probe summarization  [@Lahti2011; @Lahti2013] the microbiota profiles were generated  into three phylogenetic levels: Order-like 16S rRNA gene sequence groups (level 1); genus-like 16S rRNA gene sequence groups with a sequence similarity &gt;90% (level 2); and phylotype-like 16S rRNA gene sequence groups with a sequence similarity &gt;98% (level 3). For our study, we focus on the genus-level variation referred to as species and relatives (‘et rel.’) and use log10-transformed signals as a proxy for bacterial abundance. 


### 2.2.3 Additional variables
Maternal age as well as infant birthweight, age in weeks at the entrance to CC and sex were obtained as potential confounding variables. Table 1 shows descriptive statistics for the variables we accounted for.

## 2.3 Statistical analysis

All analyses were performed in R version 3.5 [@R2017]. 

## 2.3.1 Data preparation and visualization
The continuous covariates "age" and "breastfeeding" were standardized to ease interpretability and convergence of hierarchical linear models. There were missing values for 5 infants for the variables "breastfeeding" and "sibling" each. The missing values were imputed using predictive mean matching as implemented in the package _mice_ [@buurenFlexibleImputationMissing2019], which resulted in 10 imputed data sets. Previous to statistical modeling we applied centered-log-ratio (clr) transformation [@aitchisonStatisticalAnalysisCompositional1986] to HITchip signals using the _microbiome_ package. Euclidian distance of clr-transformed data results in Aichtison distance @aitchisonStatisticalAnalysisCompositional1986. Therefore, in order to visualize the effect of CC on overall composition over time, we could apply principal component analyses to clr-transformed HITchip signals. The resulting biplots are shown in figure 1. 

## 2.3.2 Statistical models 
To test our first hypothesis and determine whether and how much entrance to CC affects microbiota overall community composition, we performed a two way permutational multivariate analysis of variance (PERMANOVA) based on Aitchison distance. The PERMANOVA was performed using the function _adonis_ from the package _vegan_ [@R-vegan2017] with CC (CC versus no CC) interacting with time (pre versus post) as predictors controlling for breastfeeding, childsex and age. We performed differential abundance testing using Bayesian hierarchical generalized linear models with the generalized normal distribution as implemented in the _BRMS_ package [@BRMS]. Compared to the Gaussian distribution, the generalized normal distribution has an additional parameter $\alpha$, which allows the distribution to be skewed. Therefore, it can better deal with the distributional properties of bacterial abundances. Shrinkage was applied to the intercept and the slopes of the covariates and the predictor "time". Regularizing priors were chosen that make the model skeptical of an effect of childcare over time. For each genus, the same model specification was used. If a model did not converge, a stronger regularizing prior was required for the standard deviation of the varying intercept (see supplementary material for exact model specification). We used a similar model regress alpha-diversity on the same set of predictors. We could pass the multiple imputed objected created by _mice_ directly to the fitting function in the package _brms_. Finally, we used the Random Forests (RF) algorithm implemented in the package _ranger_ [@ranger] to evaluate whether we can predict childcare entrance based on 130 genus abundances for both time points.


# 3. Results 




# 4. Discussion 

We utilized both multivariate and univariate statistical approaches to test our hypotheses that CC has an effect on gut microbiota composition . Our analyses did not indicate a significant effect of CC over time and therefore both null hypotheses could not be rejected for our sample. Unexpectedly, breastfeeding and CC together explained only small amounts of variation in overall microbiota composition.  
This result is in contrast to the previously cited rodent studies [@Rea2016], but in line with @Falony2016 who recently explored the drivers of microbiota variation and similarly showed very small effect sizes for all covariates under investigation. In total, 69 of 503 (13.7%) metadata variables were significantly associated with microbiota composition and these had a cumulative (non-redundant) effect size on community variation of only 7.63%. Thus, more than 92% of microbiota variation remained unexplained suggesting additional contribution from unknown factors, such as stochastic effects and biotic interactions.  
In animal experiments the variable under investigation is usually the only factor that is changed, while in human populations the hosts show much more variation with regards to genetics and lifestyle, while the microbiota is subject to much more interactions with the environment [@Falony2016; @Rea2016].  
Nevertheless, the structure, function and stability of the infant microbiota is significantly different in composition as well as diversity from that of adults [@DeMuinck2018]. Especially in the first few weeks the gut microbiota composition is highly unstable and individual. This period is followed up by a more stable phase dominated by _Bifidobacterium_ species when breastfed and gradually goes to a more mature and diverse community during weaning due to the introduction of solid foods. It is yet unclear at what age the microbiota fully matures, but estimates range from 1 to 3 years of age [@DeMuinck2018].
This difference in microbiota dynamics in the first months of life could explain the small effect sizes we observed. Because the microbiota is so unstable it might be that there are no general effects of microbiota composition, in other words: Every infant responds in a unique way. This seems to be the case as can be seen by figures 5-14 where we do observe an average response, but a high percentage of infants shows an opposite effect. Inspecting the same figures for the remaining 120 bacterial groups, we also find highly variable trends between T0 and T1, which explains why we don’t observe an overall general effect. Another line of reasoning could be that, because of the lower stability of the infant microbiota compared to adults, it is therefore more easily ‘pushed’ or shifted due to an environmental influence such as the entrance to CC. This could still be the case. However, our data suggests the effects of this ‘push’ then are highly individual.  
Another observation is that unfortunately the period of the introduction of the first solid foods often coincided with the period under investigation, possibly combining multiple additional variables that affect the microbiota, thus obscuring separate effects. Further research would elucidate whether this is the case and we could then make classes for instance based on the percentage of solid food.  
Contrasting with previous studies we found no significant differences in the abundance of _Bifidobacterium_ between breastfed and non-breastfed infants (see figure 15). This can be explained by the addition of prebiotic fibers in infant formula’s such as Galactooligosaccharides (GOS) and Fructooligosaccharides (FOS) [@Borewicz2018]. These fibers have been added in 2002 to most infant formulae (personal communication) to emulate the bifidogenic effect of breastmilk.  
In addition to biological explanations for our observations, we encountered several methodological limitations. First, only a limited number of infants were not breastfed per group (18 infants who entered childcare and 15 infants who did not enter childcare). Larger sample sizes might be required to find an effect of breastfeeding or interactions between breastfeeding and CC. Secondly, the distributional properties of the taxa could not be addressed by solely using a gaussian model. Despite log transforming the abundances, the assumptions of normality of residuals and heterogeneity of variance often could not be met for our LMEs. We used non-parametric tests for exploratory purposes, which are not affected by the distributional properties but these do not take into account individual variation, which is a strength of LME when testing repeated measurements [@Barr2013]. A possible solution could be to analyze the data taking into consideration the individual distribution for each bacterial genus e.g. by using different link functions for the generalized linear mixed effects models. It should be noted though that for the purpose of inference as opposed to prediction, the assumptions of normality of residuals and homogeneity of variance are less important and at least mild violations should be unproblematic [@Gelman2007].  
In conclusion, based on our analyses it seems that childcare attendance does not influence the microbiota in a large and distinct way, beyond normal temporal variation. This does not mean that childcare attendance does not have an effect on the microbiota, but might imply that its effect on the microbiota are either very individual or are only observable at a different level, such as through bacterial metabolites.

