#### Title: Does early attendance to center-based childcare alter children’s intestinal microbiota?

#### Authors: Henrik Eckermann, Gerben Hermes, Willem de Vos, Carolina de Weerth

**Background:** Attending center-based childcare (CC) at three months of life can be an important life changing event that includes major stressors such as long maternal separations and frequently changing caregivers. Additionally, it implies contact with bacteria that can potentially influence the infant’s intestinal colonization pattern. These factors may alter the composition of the gut microbiota with possible implications for future health outcomes. As a part of an ongoing longitudinal study, we investigated whether attending CC as compared to being cared by the mother at home is associated with the composition of the gut microbiota and whether breastfeeding buffers the potential effect of CC on the microbiota. 
**Methods:** Stool samples of healthy community infants who entered CC (n=49) and control infants (n=49) were obtained before (T0) and four weeks after CC entrance (T1). We performed permutational multivariate ANOVA (PERMANOVA) based on Aitchison distance controlling for breastfeeding and age to look for an effect of CC over time on the overall community composition. Between and within group differences of alpha-diversity, as well as differential abundance were tested using linear mixed effects models. Finally, we also explored Bayesian hierarchical generalized linear models for differential abundance testing and comparison of alpha-diversity.
**Results:** We did not observe an effect of CC over time on overall community composition according to PERMANOVA. However, linear models predicted significantly lower alpha diversity for the CC group at T1 compared to CC at T0 or the no-CC group at T0 or T1. Furthermore, we found differences in relative abundance between and within groups. When we compared CC to no-CC at T1, or T0 to T1 within CC, we found mostly small but significant differences in bacterial relative abundance for more species than expected by chance. We did not find a significant interaction between the effect of childcare over time and breastfeeding.
**Conclusion:**
Our results suggest that entering childcare might have a small effect on microbiota composition. The lack of strong effects of this important life event in infancy together with large inter-individual variation in microbial changes, may be indicating that effects may depend on individual factors and not be generalizable at the group level.

